### ISSUE TITLE
Does not catch mis-matching react tags.

### ISSUE THREAD

**Issue by darajava** [alangpierce/sucrase#220]
Sucrase ignores malformed JSX input such as

```
<div>
</vid>
```
whereas Babel would catch this as an error. This could lead to some weird parsing and hard to find human error whilst developing.

**Comment by alangpierce** [comment]
Thanks for reporting! I actually would prefer to call this out of scope for Sucrase. Sucrase intentionally skips a lot of the validation steps that Babel (and other parsers and transpilers) does, and is able to be simpler and more efficient as a result. The general guarantee is that *if your code well-formed, Sucrase will turn it into valid JS*, but Sucrase isn't responsible for finding problems in your code.

The reason I think this is reasonable is that you should always be using some sort of linter (e.g. ESLint), and any linter will call this out as either a parse error or a lint error. In a more extreme case like TypeScript, there's already a distinction between a fast transformation step and a slow typechecking step, and Sucrase aims to make the fast transformation even faster, leaving all validation to the slower checks.

Does that make sense? I guess this particular case is annoying in that you can really run the code without problems. In most of these situations, Sucrase will read bad JS and emit bad JS and you'll find out immediately when your code fails to run.

I'll update the README to make this aspect more clear, but I'm certainly open to feedback, and let me know if you think the project should go in a different direction!
