### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by aleclarson** [alangpierce/sucrase#222]
Hey Alan, this is a really cool project. Thanks for your hard work!

As you know, a large part of Babel's appeal is its extensibility. Although sucrase avoids that bucket of worms (and for good reason), its users can still harness the power of plugins by using [nebu](https://github.com/aleclarson/nebu) after sucrase. Nebu is still very young, but I think these two projects will complement each other greatly. It uses [magic-string][1] (the same library that [Bublé][2] uses) to skip the AST-to-code generation phase in favor of simple string splits/joins (but with sourcemap support).

[1]: https://github.com/Rich-Harris/magic-string
[2]: https://github.com/Rich-Harris/buble

Cheers!

**Comment by alangpierce** [comment]
I'm doing some housekeeping and closing this out since I don't think there's anything actionable here, but feel free to reopen/comment if you disagree!
