### ISSUE TITLE
determine spec compliance with kangax test suite

### ISSUE THREAD

**Issue by k4b7** [alangpierce/sucrase#226]
It would be interesting to see how spec compliant the transformed code is.  https://github.com/kangax/compat-table has a set of tests, not sure how much work it would be to adapt them to run with sucrase.

**Comment by alangpierce** [comment]
Hey Kevin! Yep, Sucrase doesn't do a lot that would apply to a compatibility table like that, mostly just the class fields implementation. There might be similar compat tests for JSX/Flow/TypeScript out there (and if not, maybe there should be), but for now I think running on open source projects is the best way to be confident that Surcase is correct.
