### ISSUE TITLE
Class Fields

### ISSUE THREAD

**Issue by rkichenama** [alangpierce/sucrase#235]
When attempting to test out the transpiling via the online tool, I found that it would throw an error when attempting to process class properties; Expected `rhsEndIndex` on class field assignment.

```
import React, { Component } from 'react';
import PropTypes from 'prop-types';

export default class Paginate extends Component {
  static propTypes = {
    count: PropTypes.number.isRequired
  }

  render () {
    const {
      props: { count, size }
    } = this;

    return (
      <section className='paginate'>
        <div>{count} total row(s)</div>
      </section>
    );
  }
}
```

**Comment by aleclarson** [comment]
I think I found a related bug with a different error message. [link](https://sucrase.io/#code=export%20class%20Observer%20%7B%0A%20%20update%20%3D%20(v%3A%20any)%20%3D%3E%20%7B%7D%0A%20%20complete%20%3D%20()%20%3D%3E%20%7B%7D%0A%20%20error%20%3D%20(err%3A%20any)%20%3D%3E%20%7B%7D%0A%7D%0A%0Aexport%20default%20function()%20%7B%7D%0A)

If you put a semi-colon after the last class field, it compiles fine. And the error message changes if you remove the `export default` at the bottom.
