### ISSUE TITLE
JSX fragments are broken

### ISSUE THREAD

**Issue by arv** [alangpierce/sucrase#254]
Empty fragments and fragments without whitespace do not work

https://sucrase.io/#selectedTransforms=jsx,imports&compareWithTypeScript=true&code=const%20c%20%3D%20%3C%3E%3C%2F%3E%3B%0A

https://sucrase.io/#selectedTransforms=jsx,imports&compareWithTypeScript=true&code=const%20c%20%3D%20%3C%3E%3Ca%2F%3E%3C%2F%3E%3B%0A

**Comment by alangpierce** [comment]
Thanks! Hopefully shouldn't be too bad to fix.

By the way, if you happen to know any significant open source projects that use JSX fragments, would be good to hear. Most of correctness issues in Sucrase have been found by running it on codebases I can find, and when I added fragment support I just wrote a few test cases myself, but obviously there were plenty of missing edge cases like these.

**Comment by arv** [comment]
I don't know of any code base that uses them. You could just grab a few of the tests from Babel to ensure compatibility.
