### ISSUE TITLE
Did you try optimize sources by Prepack?

### ISSUE THREAD

**Issue by MaxGraey** [alangpierce/sucrase#269]
https://github.com/facebook/prepack

**Comment by alangpierce** [comment]
I haven't tried it out, but I'll take a look when I get a chance. It looks to me like Prepack is most useful for packages with an expensive up-front initialization cost, and Sucrase is a relatively small project (meaning relatively little module init work) and I don't think it precomputes anything at init time, so I suspect that Prepack won't actually be benificial here. But it certainly seems worth trying.

**Comment by MaxGraey** [comment]
Hmm, may be this not good idea for library. Ok, I'll close this
