### ISSUE TITLE
Removing extension from "main" in Package.json for ESM/CJS interop

### ISSUE THREAD

**Issue by SMotaal** [alangpierce/sucrase#303]
https://github.com/alangpierce/sucrase/blob/15debf701596bd2a1d7564d8f1e147da357dfb56/package.json#L7

Currently Node (with `--experimental-modules`) can decide to either load '.mjs' or '.js' depending on the mode (ie importing into ES or importing/requiring into cjs) however this only works if the "main" in `package.json` does not specify an explicit extension.

```json
{
  "main": "dist/index"
}
```

To the best of my knowledge, omitting the extension should not have any side effects in earlier versions of Node, but it is worth verifying on your end if you are willing to consider making this minor change.

Thanks

**Comment by alangpierce** [comment]
Interesting, thanks for calling out. I must admit, I never ended up testing Sucrase with `--experimental-modules`, even though certainly the intention is to use that mode in the long run. A possibility is to use modules for all internal Sucrase scripts, although given the warning and the need to support node 8, it might be a bit early for that. Regardless, happy to make the change you suggested, although I'll want to do a little more research/testing to make sure it doesn't cause trouble.

**Comment by SMotaal** [comment]
I would hold off on existing projects re —exm but encourage starting new projects with it along with rollup to ensure portability. Experimental modules are really intended to gain insights from pain points but not intended for transitive codebase upgrades.

Obviously picking up on small queues like omitting extension is not to drastic to take for granted.

Saleh Abdel Motaal
