### ISSUE TITLE
Optional argument in arrow functions doesn't compile

### ISSUE THREAD

**Issue by kiliancs** [alangpierce/sucrase#387]
This doesn't compile with Sucrase 3.9.1 but compiles with TypeScript:

```ts
const test = (a?) => a;
```

See to compare the results:

https://sucrase.io/#compareWithBabel=false&compareWithTypeScript=true&code=%2F%2F%20works%20with%20tsc%2C%20doesn't%20with%20sucrase%0Aconst%20test%20%3D%20(a%3F)%20%3D%3E%20a%3B%0A%0A%2F%2F%20works%20in%20both%20tsc%20and%20sucrase%0Afunction%20test2(a%3F)%20%7B%0A%20%20return%20a%3B%0A%7D

**Comment by alangpierce** [comment]
Haha, wow, I didn't know that syntax existed. Should be a pretty easy fix, thanks for reporting.

**Comment by alangpierce** [comment]
Fixed and released in 3.9.2, and I and re-published the website, so your link above works now.

**Comment by kiliancs** [comment]
Impresive! Thank you so much :)
