### ISSUE TITLE
Async arrow function with multiline TS generics results in invalid output

### ISSUE THREAD

**Issue by kiliancs** [alangpierce/sucrase#396]
With sucrase 3.9.3, the this valid TypeScript results in invalid code:

```ts
var multilineGenerics = async <
    A extends B // this sometimes can be quite long
>(x) => x;

```

https://sucrase.io/#code=var%20multilineGenerics%20%3D%20async%20%3C%0A%20%20%20%20A%20extends%20B%20%2F%2F%20this%20sometimes%20can%20be%20quite%20long%0A%3E(x)%20%3D%3E%20x%3B%0A

**Comment by kiliancs** [comment]
I imagine in this case the solution would be to move `async` to the same line as the parameters:

```js
var multilineGenerics = 

async (x) => x;
```

**Comment by alangpierce** [comment]
Interesting, thanks. Arrow function parsing sure is tricky.
