### ISSUE TITLE
Object literal exported as default doesn't exclude types

### ISSUE THREAD

**Issue by kiliancs** [alangpierce/sucrase#400]
Using Sucrase 3.9.4

```ts
type T = number;

const foo = 3;

export default { T, foo }
```

results in

```js
"use strict";Object.defineProperty(exports, "__esModule", {value: true});

const foo = 3;

exports. default = { T, foo }
```

https://sucrase.io/#code=type%20T%20%3D%20number%3B%0A%0Aconst%20foo%20%3D%203%3B%0A%0Aexport%20default%20%7B%20T%2C%20foo%20%7D%0A

**Comment by kiliancs** [comment]
Uhmm I guess this could fall under https://github.com/alangpierce/sucrase/issues/398 actually. This case was just not contemplated there.

**Comment by alangpierce** [comment]
Hmm I think that's not valid TypeScript. You can't use a type in an object literal, including in an export default statement.

Here's the error in the TS playground:
<img width="714" alt="screen shot 2019-01-09 at 1 03 02 pm" src="https://user-images.githubusercontent.com/211605/50928205-f2603600-140e-11e9-906d-52820113ccc3.png">

**Comment by kiliancs** [comment]
Ah, of curse. Never mind then! Thanks for checking.
