### ISSUE TITLE
TypeScript import = syntax isn't always properly elided

### ISSUE THREAD

**Issue by alangpierce** [alangpierce/sucrase#422]
Sucrase gives the wrong output for this TypeScript code:
```typescript
import A from './A';
import B = A.B;
```
The correct approach is to elide both imports because the second is a type-only import, which we can know statically because `import =` only is allowed for `require` and for accessing types (I believe).

[Playground example](https://sucrase.io/#compareWithTypeScript=true&code=%0Aimport%20D%20from%20'.%2Fb'%3B%0Aimport%20A%20%3D%20B.C%3B)

**Comment by alangpierce** [comment]
Looks like I also need to handle `require` forms of `import =`, e.g. this code:
```typescript
import a = require('a');
```
should elide the import since `a` is never used and might be a type.

**Comment by jeremy-coleman** [comment]
maybe helpful idk

```ts
import { createSourceFile, ScriptTarget } from 'typescript';
var jetpack = require('fs-jetpack')
const srcFile = (v) => createSourceFile(v, jetpack.read(v).toString(), ScriptTarget.Latest)
console.log(srcFile('./src/main.ts'))
```
