### ISSUE TITLE
SyntaxError (comment inside expression)

### ISSUE THREAD

**Issue by c-johnson** [alangpierce/sucrase#428]
I'm not even sure if this is technically valid Javascript, but the following statement fails with a SyntaxError using sucrase 3.9.6 with the JSX transform:

`let thing = "sup" /*/*/;`

It does work in both webpack and chrome. Esprima also seems to think it's valid (http://esprima.org/demo/validate.html).

**Comment by alangpierce** [comment]
Thanks for reporting! Seems like valid JS to me. Distinguishing regular expressions from comments has some edge cases, and looks like something goes wrong in the Sucrase parser.

**Comment by alangpierce** [comment]
I just released a fix for this in 3.10.0.
