### ISSUE TITLE
Dynamic imports and webpack code splitting

### ISSUE THREAD

**Issue by Frando** [alangpierce/sucrase#446]
Hi,
has someone gotten Sucrase to work with dynamic imports and webpack code splitting?

If I enable the "imports" transform, the import(...) parts are translated to require, which - I think - makes webpack not do code splitting.
If I disable the imports transform, sucrase cannot parse a dynamic import statement and gives errors.

Any ways out?

**Comment by Frando** [comment]
Oh, it just works.

**Comment by alangpierce** [comment]
@Frando glad to hear it's working for you. Are you still getting Sucrase errors on dynamic import with the imports transform disabled? That's supposed to output dynamic imports correctly, so would be good to hear if there's a case where that breaks.

Example of it working: https://sucrase.io/#selectedTransforms=&code=%0Aconst%20foo%20%3D%20import('.%2Ffoo')%3B
