### ISSUE TITLE
Multi-line imports produce blank strings

### ISSUE THREAD

**Issue by sh7dm** [alangpierce/sucrase#452]
![image](https://user-images.githubusercontent.com/19504461/58529622-46b05a80-81e4-11e9-80bf-7dc238f49f6a.png)
![image](https://user-images.githubusercontent.com/19504461/58529639-50d25900-81e4-11e9-9755-089614f3d94e.png)

**Comment by alangpierce** [comment]
Hi, sorry for the delayed response! Unless I'm misunderstanding your report, this behavior is expected. Sucrase intentionally compiles code in such a way that line numbers in the compiled code line match line numbers in the source code. For example, that makes stack traces useful even if you haven't configured source maps.

One aspect of that behavior is that when a multi-line expression compiles to a single-line expression, Sucrase needs to insert blank lines.
