### ISSUE TITLE
add caching to file

### ISSUE THREAD

**Issue by a-x-** [alangpierce/sucrase#460]
Speed it up dramatically between restarts. save hash-sums to node_modules/.cache dir

Look like babel, terser, or eslint does it

**Comment by alangpierce** [comment]
Similar to https://github.com/alangpierce/sucrase/issues/459 , I prefer to view the core Sucrase `transform` function as a low-level primitive that build systems can cache if they want. Webpack's `cache-loader` is one example, if you're invoking Sucrase via webpack.

Still, from my experience, caching makes things more fragile, and I personally never use Sucrase with a cache. Before my team switched to Sucrase, we used Babel's caching for the require hook and for webpack builds, and in both cases, we had issues where the cache would be stale and give incorrect code, so everyone on the team had to learn how to clear the cache as a troubleshooting step. It also has performance overhead; at least with Babel 6, the performance of loading and saving the cache was often slower than the full Sucrase build when running a small number of tests.

One of my goals with Sucrase is for it to be *so fast that you don't need to cache it*. Maybe that's optimistic, and you're still welcome to cache the results in any integration, but I'd prefer to not have it built into the core Sucrase library.
