### ISSUE TITLE
Clarifying error messages when incorrect options are passed

### ISSUE THREAD

**Issue by ansballard** [alangpierce/sucrase#467]
Sucrase version: 3.10.1
Node version: 11.15.0
NPM version: 6.7.0

When passing options to sucrase (through a build plugin or directly to transform), if you do not pass `transforms`, or don't pass it as an array, you will get the error:

> Cannot read property 'includes' of undefined

This did not make it very obvious that I had passed `transform` instead of `transforms`, and I had to jump through the stack trace to figure out what was actually happening. Instead of that, I think it would be helpful to first check that `options.transforms` exists ([Line number](https://github.com/alangpierce/sucrase/blob/bd1ee84c0a7898a1f21754c79b654ff6c9e1605b/src/index.ts#L120)), and that it is an array. If not, a helpful message can be returned and the user goes on about their life.

Thank you for the awesome tool!

**Comment by alangpierce** [comment]
Thanks, agreed that validation could be a lot better here, and integration usability in general could use some improvement. I'll try getting runtime checking working for the `Options` type, either manual or using some sort of auto-generator from the TS type.
