### ISSUE TITLE
Nullish coalesce fails when returning an empty object

### ISSUE THREAD

**Issue by jbellsey** [alangpierce/sucrase#505]
Trying to use an empty object as the fallback will fail:

```
const x = null ?? {}
// compiles to:
_nullishCoalesce(null, () => {})
// evaluates to undefined!
```

**Comment by alangpierce** [comment]
Thanks for reporting! Looks like the right fix is to always wrap the RHS expression in parens here. This only affects nullish coalescing, not optional chaining, since optional chaining always starts the arrow body with `_` or `delete`.

I'll work on a fix soon.
