### ISSUE TITLE
Hoist Jest mocks

### ISSUE THREAD

**Issue by Rugvip** [alangpierce/sucrase#539]
I tried using Sucrase to speed up Jest tests, and ran into issues with module mocks not being hoisted up above imports. Without automatic hoisting, the `jest.mock`/`jest.unmock` calls need to be manually placed above the imports, which isn't optimal.

This is for example how `ts-jest` does hoisting: https://github.com/kulshekhar/ts-jest/blob/a6bcec48ef28791235b3eba0b3f2bd1a944ba5b8/src/transformers/hoist-jest.ts

Would be awesome to have this implemented! I could have a look at it as well, given some pointers.

**Comment by Raynos** [comment]
That's called `JestScript`

If your changing the order of execution of javascript statements in a file that ends with `.js` then it's not JavaScript.

There are transforms for `jsx` & `flow` ; I guess you can write a transformer and add it to https://github.com/alangpierce/sucrase/tree/master/src/transformers

**Comment by Rugvip** [comment]
Fixed by #540
