### ISSUE TITLE
Add column data to source map mappings

### ISSUE THREAD

**Issue by edeustace** [alangpierce/sucrase#541]
Are you planning on adding column information to source map `mappings`?

Some context: I'm using sucrase in a rollup build in a chain of rollup plugins. When building the final source map for the given chunk, rollup attempts to trace the segments by stepping through the chain of sourcemaps that were generated by the plugins. The lack of column information in the sucrase source maps causes this tracing to stop and so causes the source map to be incomplete.

**Comment by forivall** [comment]
@edeustace I implemented it!
