### ISSUE TITLE
Sucrase creates folder recursion on build

### ISSUE THREAD

**Issue by JVKdouk** [alangpierce/sucrase#548]
Hi, I've been using Sucrase for my TS Express project and found something a little bit weird:
Whenever I try to build using the command:

`sucrase ./ -d ./dist --transforms typescript,imports`

Sucrase creates dist inside dist, generating a long chain of folders with name "dist". In many tutorials I have seen, people usually creates a "src" folder for the code and a "dist" for the sucrase build, but in my case, I want the src to be at root.
What can I do?

Node v14.7.0
Sucrase v3.15.0

**Comment by BlueGhostGH** [comment]
I've had this happen to me as well, please fix this IMMEDIATELY, it's a super annoying bug, I wasted 15 minutes getting rid of the 10k+ recursive directories generated.

**Comment by JVKdouk** [comment]
Apparently this library is dead... I started using tsc and ts-node-dev
Everything works like a charm now!

**Comment by BlueGhostGH** [comment]
I did the exact same thing, everything works like a charm indeed.
