### ISSUE TITLE
Named export from destructuring doesn't work

### ISSUE THREAD

**Issue by brapifra** [alangpierce/sucrase#563]
It looks like named exports that come from destructuring an object don't get compiled:
```typescript
const { someFieldIWantToExport } = someObject;

export { someFieldIWantToExport }; // This does not get exported as it should
```

### Example
https://sucrase.io/#compressedCode=H4sIAHh6w18AA8vMLcgvKlEISk1MLtFRqFZwzgcK5KXmlSjUKqQV5ecqKBWBpJSsubiS8%2FOKS4BKSotTg0sSS1KBKmwhGq0V9PUVQjIyixVS8lOL89RLFMrzi7K5uGCiIF4xiAcxAm4AVLseTABoSWoF2D3ItsDEUlLTEktzShQcCwqACgGDCiqfuQAAAA%3D%3D

**Comment by alangpierce** [comment]
Thanks for reporting! It looks like the `someFieldIWantToExport` declaration is being misidentified by the parser as `ObjectShorthandBlockScopedDeclaration` when it should be `ObjectShorthandTopLevelDeclaration`, so it ends up being elided like a type.
