### ISSUE TITLE
Add support for `override` token from TS 4.3

### ISSUE THREAD

**Issue by marvinhagemeister** [alangpierce/sucrase#629]
With the recent Typescript 4.3 release there is a new `override` keyword that can be used on class methods. See documentation here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#override-and-the---noimplicitoverride-flag

Currently sucrase throws an unexpected token error. From what I'm reading in the documentation it looks like we can safely just strip the keyword without doing any further transformations.

**Comment by alangpierce** [comment]
I just released `override` support (plus support for all other new TS 4.2 and 4.3 syntax) as Sucrase 3.20.0.

**Comment by marvinhagemeister** [comment]
@alangpierce Sweet thank you so much 🙌
