### ISSUE TITLE
Javascript out of memory 

### ISSUE THREAD

**Issue by HomyeeKing** [alangpierce/sucrase#662]
![image](https://user-images.githubusercontent.com/49113249/139784933-2030b660-db6f-415c-b2ba-38e738b4aa4b.png)

only several lines of code ,
I can run it at `node` runtime but browser

```js
import { transform } from "sucrase";

export function compileForPreview(code) {
  return transform(code, {
    transforms: ["jsx"],
    disableESTransforms: true,
    jsxFragmentPragma: "Rax.createElement",
    jsxPragma: "Rax.Fragment",
  }).code;
}

const code = `
import { createElement } from "rax";
const App = () => {
  return (
    <div>
      <span>Hello Rax</span>
    </div>
  );
};
`


console.log(compileForPreview(code));

```

**Comment by alangpierce** [comment]
Sorry for not responding previously to this. I tried to reproduce the out-of-memory issue, but it's working for me, so I'll close this out. Feel free to re-open or file a new issue if you still see any problems, though.
