### ISSUE TITLE
How do we include json files to compile result?

### ISSUE THREAD

**Issue by Mednoob** [alangpierce/sucrase#665]
I was trying to compile my project using this command:
```
sucrase ./src -d sucrase-dist --transforms typescript,imports
```

Sucrase did compile the project, but it didn't include json files. I have specified `resolveJsonModule` to `true` in tsconfig.json. So, how do I include json files in the compile result?

**Comment by alangpierce** [comment]
Hi @Mednoob, at the moment, the `sucrase` CLI only deals with JavaScript/TypeScript files; it won't copy other files that happen to be in your directory. Sucrase also doesn't follow import statements; it's really just processing the JS/TS files in the directory.

I think there are two ways you could proceed:
* Write a build script that runs `sucrase` and also separately copies the JSON files into the `sucrase-dist` directory. It looks like https://superuser.com/questions/299938/how-can-i-recursively-copy-files-by-file-extension-preserving-directory-structu/299999 has some options for copying all files of a particular type preserving directory structure, or you might be able to do something more specialized.
* Depending on context, you may be able to use an alternative build system approach that doesn't use the Sucrase CLI. If you're running the code directly in Node, you can compile on-the-fly using `sucrase-node` or `sucrase/register`, no need for an output directory. If you're building for the browser, you can usually use a bundler like webpack that can compile your TS files as it reads them. It's not always possible, but I've found that especially for development, it's nice to avoid an explicit output directory.

I'd be happy to accept a PR that adds an option to copy non-JS/TS files when running the Sucrase CLI. It looks like in the Babel CLI the `--copy-files` option will copy other files in the directory ( https://babeljs.io/docs/en/babel-cli#copy-files ), so it seems reasonable to go with that arg name and behavior. The CLI code is all in `src/cli.ts`.
