### ISSUE TITLE
support type modifers on import names in Typescript

### ISSUE THREAD

**Issue by jquense** [alangpierce/sucrase#668]
I'm guessing this needs parser updates since it's new syntax but TS 4.5 introduced: https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names

**Comment by alangpierce** [comment]
Thanks for reporting! Sorry for the delay, catching up on the issue backlog now. I implemented the new TS import/export type syntax and just released it in version 3.23.0.
