### ISSUE TITLE
Babel + browserlist == sucrase?

### ISSUE THREAD

**Issue by yairEO** [alangpierce/sucrase#693]
> "... Instead of compiling a large range of JS features to be able to work in Internet Explorer, Sucrase assumes that you're developing with a recent browser or recent Node.js version, so it focuses on compiling non-standard language extensions: JSX, TypeScript, and Flow...."

Isn't that the same as defining *browserlist* for Babel to use so it will only use the **needed** transformers?

**Comment by alangpierce** [comment]
Hi @yairEO , you can definitely configure Babel to have the same behavior of Sucrase. The advantage of Sucrase is that it's much faster than Babel, even when Babel only has a small number of transforms enabled. You might also find Sucrase easier to configure if it fits your use case.

**Comment by yairEO** [comment]
But still the [comparison page](https://sucrase.io/) is unfair because there is no way to set `browerslist` configuration for Babel or see which plugins are configured, which both are highly related to the speed of compilation 

How can I, as a developer in a large firm with very complex systems, can decide if I should spend a full day or two switching to Sucrase, based on that benchmark page..  is there a project with a comparison which can be cloned and configured to better match a current app's babel setup?

**Comment by yairEO** [comment]
From the README:

![image](https://user-images.githubusercontent.com/845031/164979843-8d23431e-3903-4f9c-bad2-13518ff6dd56.png)

This sentence *"transformed by default"* is very confusing and suggests `sucrase` does not take `browserlist` into account, and no mentioned of `browserlist` is to be found in the README, which to me is odd. Why would I want to transform code which is explicitly meant for **latest Chrome** users?

I do have experimental stuff (like legacy decorators) which must be transformed because it's not a valid js code, but other than that, just plain JSX.
