### ISSUE TITLE
Possible to support SystemJS module ?

### ISSUE THREAD

**Issue by wenerme** [alangpierce/sucrase#761]
Without imports will transform to cjs, with imports will use esm syntax, but want to eval in browser, SystemJS is the best option to provide a module system.

**Comment by alangpierce** [comment]
Hi, thanks for the request! Unfortunately, I consider SystemJS to be out of scope for Sucrase. My understanding is that SystemJS is useful for supporting older browsers that don't have support for native ES modules, but Sucrase is focused on supporting the latest browser/node versions. I'm sure SystemJS support would be useful for some people, but it's important for Sucrase to keep a small scope to avoid getting too complex. Closing this issue, but let me know if I'm misunderstanding.
