### ISSUE TITLE
Dynamic import not act as expected as typescript transpiled

### ISSUE THREAD

**Issue by miserylee** [alangpierce/sucrase#778]
Here is the example:

https://sucrase.io/#compareWithBabel=false&compareWithTypeScript=true&code=import%20b%20from%20'a'%3B%0A%0Aasync%20function%20a%20()%20%7B%0A%20%20console.log(b)%3B%0A%20%20const%20c%20%3D%20await%20import('a')%3B%0A%20%20console.log(c)%3B%0A%20%20console.log(c.default)%3B%0A%7D

While static import is transpiled to use `_interopRequireDefault`, but dynamic import is not transpiled to use `__importStar`, so in runtime `c.default` is not defined.

**Comment by alangpierce** [comment]
Thanks for reporting! I just released a fix in 3.31.0.
