### ISSUE TITLE
jsx: preserve

### ISSUE THREAD

**Issue by maor-benami** [alangpierce/sucrase#780]
Is it possible to config jsx:preserve?

**Comment by alangpierce** [comment]
Hi @maor-benami , thanks for the question. At the moment there's no built-in support for preserving JSX, but I think it shouldn't be so difficult to add as a new `jsxRuntime` option. I haven't had a lot of time to work on this project recently, but I think I should have some time in the near future, and this is definitely on my radar as one of the higher-value things to add.

In the meantime, there are a few tricks/hacks described in https://github.com/alangpierce/sucrase/issues/559 to get it working now.

**Comment by alangpierce** [comment]
I just released support for this in 3.31.0. To preserve JSX, include `jsx` in the list of transforms and set `jsxRuntime: "preserve"` in the configuration.
