### ISSUE TITLE
Question: strict mode

### ISSUE THREAD

**Issue by Smrtnyk** [alangpierce/sucrase#787]
Is it possible to avoid output of `"use strict"` in transpiled files?
we have some jest tests that fail because of that, and we need them to be in non strict mode

**Comment by alangpierce** [comment]
Hi @Smrtnyk , sorry, Sucrase doesn't directly support targeting non-strict mode. Sucrase assumes that all input code uses modules, which always run in strict mode. Generally, Sucrase tries to keep configuration minimal, so it doesn't have options for older use cases like non-strict mode.

If you'd like to run Jest tests with Sucrase and without strict mode, I'd recommend writing your own Jest plugin based off of https://github.com/alangpierce/sucrase/blob/main/integrations/jest-plugin/src/index.ts that just removes the `"use strict"` with a line like:
```ts
code = code.replace(/"use strict";/, '');
```

Alternatively, if you happen to never use `import`/`export` syntax, you may be able to get the same effect by disabling the `imports` transform by passing in different transforms in the Sucrase options when configuring the Jest plugin.

**Comment by Smrtnyk** [comment]
Thanks @alangpierce  for the elaborate answer
