### ISSUE TITLE
TypeScript: `x < y >= z` is incorrectly interpreted as a type argument list

### ISSUE THREAD

**Issue by evanw** [alangpierce/sucrase#797]
Here's a full example ([link](https://sucrase.io/#transforms=typescript&compareWithTypeScript=true&code=fn(x%20%3C%20y%2C%20x%20%3E%3D%20y)%0A)):

```ts
// Input
fn(x < y, x >= y)

// Sucrase
fn(x = y)

// TypeScript
fn(x < y, x >= y);
```

Specifically TypeScript's `parseTypeArgumentsInExpression` function backtracks unless the trailing `>` comes from a `>` real token. This is subtle because TypeScript's type argument parser normally strips off the leading `>` from a token, which is why `>>` works in `a<b<c>>(d)`. But it turns out that should only be done when you're in a type context. When you're in an expression context, the trailing `>` must not come from a token that has anything else after it. So for example `a<b<c>>=(d)` should not be considered a type argument list because `parseTypeArgumentsInExpression` encounters a `>=` token.

I just fixed this bug in esbuild: https://github.com/evanw/esbuild/issues/3111. I'm reporting it here because Sucrase appears to also have this issue. The bug does not introduce a syntax error, which means the problematic output might be missed before releasing it, so I considered this bug to be higher severity.

**Comment by alangpierce** [comment]
Thank you letting me know! Agreed that it's higher severity.
