### ISSUE TITLE
glob lib dependency, depends on Inflight lib which is now introducing a security vulnerability

### ISSUE THREAD

**Issue by elvisjfer** [alangpierce/sucrase#821]
inflight@1.0.6 has a vulnerability of "Missing Release of Resource after Effective Lifetime".
https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116
Nx depends on glob@7.1.6 which depends on inflight@1.0.6.

Expected Behavior
No vulnerability.
As suggested in https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116
glob lib should be updated to latest 10.x.x version (which is not depends on inflight)

Steps to Reproduce
package.json file includes:
`"glob": "7.1.6",`

Navigate to https://security.snyk.io/vuln/?search=inflight

**Comment by pnappa** [comment]
I just opened #822 which should resolve this.

**Comment by alangpierce** [comment]
Fixed in #822 and released in v3.35.0.
