### ISSUE TITLE
support absolute import with baseUrl

### ISSUE THREAD

**Issue by andriyor** [alangpierce/sucrase#831]
I have tsconfig with such baseUrl
`"baseUrl": ".",`

transpilation produce such error:
` Cannot find module 'src/hivemind/experiments' from 'src/components/invoices/invoices-page/invoice-banner.tsx'`

**Comment by alangpierce** [comment]
Hi, sorry for the delay. Sucrase, like the official TypeScript compiler, doesn't modify import statements at transpile time. The idea is that you should write paths that work with your runtime (e.g. Node) or bundler (e.g. Webpack), and if you want something like absolute import, you should configure that in your runtime or bundler settings. The `baseUrl` TypeScript config (which Sucrase doesn't need) is so the TypeScript typechecker can match the runtime/bundler settings, but it isn't meant to change anything about runtime file resolution.

See the comments from the TypeScript team in this issue for the rationale: https://github.com/microsoft/TypeScript/issues/26722
