### ISSUE TITLE
Is Sucrase support targeting ES3?

### ISSUE THREAD

**Issue by aztack** [alangpierce/sucrase#832]
I'm writing plugin targeting a rather old JavaScript engine which support only ES3 syntax. 

I've tried compile my *.ts to es3 with TypeScript which have no problem. But I want to try do the compiling on-the-fly which will much ease the building process.

So, is Sucrase support targeting to ES3?

**Comment by alangpierce** [comment]
Hi, sorry for the delay. No, Sucrase doesn't support targeting ES3. It supports a few ES transforms for past pragmatic reasons, but generally isn't meant for targeting old browsers. For compiling on-the-fly, you could look at `ts-node` or related tools, which can work with the official TypeScript compiler or other compilers.
